export interface Member {
    no: number;
    namaAnggota: string;
    npa: string;
    nik: string;
    tempatLahir: string;
    tanggalLahir: string;
    provinsi: string;
    foto: string;
    qrCode: string;
    whatsapp: string;
    status: string;
  }
  
  export const DummyData: Member[] = [
    {
      no: 1,
      namaAnggota: 'Muhammad Abdul HAlim S.Kom',
      npa: '12345',
      nik: '1234567890123456',
      tempatLahir: 'Jakarta',
      tanggalLahir: '01-01-1990',
      provinsi: 'DKI Jakarta',
      foto: '/assets/ilustrasi.png',
      qrCode: '/assets/ilustrasi.png',
      whatsapp: '08123456789',
      status: 'Active',
    },
    {
      no: 2,
      namaAnggota: 'Jane Doe',
      npa: '67890',
      nik: '6543210987654321',
      tempatLahir: 'Bandung',
      tanggalLahir: '02-02-1992',
      provinsi: 'Jawa Barat',
      foto: '/icon/pencil.png',
      qrCode: '/assets/ilustrasi.png',
      whatsapp: '08198765432',
      status: 'Inactive',
    },
    {
      no: 3,
      namaAnggota: 'Muhammad Salman alfarisi S.Kom',
      npa: '12345',
      nik: '1234567890123456',
      tempatLahir: 'Jakarta',
      tanggalLahir: '01-01-1990',
      provinsi: 'DKI Jakarta',
      foto: '/assets/ilustrasi.png',
      qrCode: '/assets/ilustrasi.png',
      whatsapp: '08123456789',
      status: 'Active',
    },
    {
      no: 4,
      namaAnggota: 'Aisyah nurul Hasanah S.Pd',
      npa: '12345',
      nik: '1234567890123456',
      tempatLahir: 'Jakarta',
      tanggalLahir: '01-01-1990',
      provinsi: 'DKI Jakarta',
      foto: '/assets/ilustrasi.png',
      qrCode: '/assets/ilustrasi.png',
      whatsapp: '08123456789',
      status: 'Active',
    },
    {
        no: 1,
        namaAnggota: 'Muhammad Abdul HAlim S.Kom',
        npa: '12345',
        nik: '1234567890123456',
        tempatLahir: 'Jakarta',
        tanggalLahir: '01-01-1990',
        provinsi: 'DKI Jakarta',
        foto: '/assets/ilustrasi.png',
        qrCode: '/assets/ilustrasi.png',
        whatsapp: '08123456789',
        status: 'Active',
      },
      {
        no: 2,
        namaAnggota: 'Jane Doe',
        npa: '67890',
        nik: '6543210987654321',
        tempatLahir: 'Bandung',
        tanggalLahir: '02-02-1992',
        provinsi: 'Jawa Barat',
        foto: '/icon/pencil.png',
        qrCode: '/assets/ilustrasi.png',
        whatsapp: '08198765432',
        status: 'Inactive',
      },
      {
        no: 3,
        namaAnggota: 'Muhammad Salman alfarisi S.Kom',
        npa: '12345',
        nik: '1234567890123456',
        tempatLahir: 'Jakarta',
        tanggalLahir: '01-01-1990',
        provinsi: 'DKI Jakarta',
        foto: '/assets/ilustrasi.png',
        qrCode: '/assets/ilustrasi.png',
        whatsapp: '08123456789',
        status: 'Active',
      },
      {
        no: 4,
        namaAnggota: 'Aisyah nurul Hasanah S.Pd',
        npa: '12345',
        nik: '1234567890123456',
        tempatLahir: 'Jakarta',
        tanggalLahir: '01-01-1990',
        provinsi: 'DKI Jakarta',
        foto: '/assets/ilustrasi.png',
        qrCode: '/assets/ilustrasi.png',
        whatsapp: '08123456789',
        status: 'Active',
      },
      {
        no: 1,
        namaAnggota: 'Muhammad Abdul HAlim S.Kom',
        npa: '12345',
        nik: '1234567890123456',
        tempatLahir: 'Jakarta',
        tanggalLahir: '01-01-1990',
        provinsi: 'DKI Jakarta',
        foto: '/assets/ilustrasi.png',
        qrCode: '/assets/ilustrasi.png',
        whatsapp: '08123456789',
        status: 'Active',
      },
      {
        no: 2,
        namaAnggota: 'Jane Doe',
        npa: '67890',
        nik: '6543210987654321',
        tempatLahir: 'Bandung',
        tanggalLahir: '02-02-1992',
        provinsi: 'Jawa Barat',
        foto: '/icon/pencil.png',
        qrCode: '/assets/ilustrasi.png',
        whatsapp: '08198765432',
        status: 'Inactive',
      },
      {
        no: 3,
        namaAnggota: 'Muhammad Salman alfarisi S.Kom',
        npa: '12345',
        nik: '1234567890123456',
        tempatLahir: 'Jakarta',
        tanggalLahir: '01-01-1990',
        provinsi: 'DKI Jakarta',
        foto: '/assets/ilustrasi.png',
        qrCode: '/assets/ilustrasi.png',
        whatsapp: '08123456789',
        status: 'Active',
      },
      {
        no: 4,
        namaAnggota: 'Aisyah nurul Hasanah S.Pd',
        npa: '12345',
        nik: '1234567890123456',
        tempatLahir: 'Jakarta',
        tanggalLahir: '01-01-1990',
        provinsi: 'DKI Jakarta',
        foto: '/assets/ilustrasi.png',
        qrCode: '/assets/ilustrasi.png',
        whatsapp: '08123456789',
        status: 'Active',
      },
      {
        no: 1,
        namaAnggota: 'Muhammad Abdul HAlim S.Kom',
        npa: '12345',
        nik: '1234567890123456',
        tempatLahir: 'Jakarta',
        tanggalLahir: '01-01-1990',
        provinsi: 'DKI Jakarta',
        foto: '/assets/ilustrasi.png',
        qrCode: '/assets/ilustrasi.png',
        whatsapp: '08123456789',
        status: 'Active',
      },
      {
        no: 2,
        namaAnggota: 'Jane Doe',
        npa: '67890',
        nik: '6543210987654321',
        tempatLahir: 'Bandung',
        tanggalLahir: '02-02-1992',
        provinsi: 'Jawa Barat',
        foto: '/icon/pencil.png',
        qrCode: '/assets/ilustrasi.png',
        whatsapp: '08198765432',
        status: 'Inactive',
      },
      {
        no: 3,
        namaAnggota: 'Muhammad Salman alfarisi S.Kom',
        npa: '12345',
        nik: '1234567890123456',
        tempatLahir: 'Jakarta',
        tanggalLahir: '01-01-1990',
        provinsi: 'DKI Jakarta',
        foto: '/assets/ilustrasi.png',
        qrCode: '/assets/ilustrasi.png',
        whatsapp: '08123456789',
        status: 'Active',
      },
      {
        no: 4,
        namaAnggota: 'Aisyah nurul Hasanah S.Pd',
        npa: '12345',
        nik: '1234567890123456',
        tempatLahir: 'Jakarta',
        tanggalLahir: '01-01-1990',
        provinsi: 'DKI Jakarta',
        foto: '/assets/ilustrasi.png',
        qrCode: '/assets/ilustrasi.png',
        whatsapp: '08123456789',
        status: 'Active',
      },
      {
          no: 1,
          namaAnggota: 'Muhammad Abdul HAlim S.Kom',
          npa: '12345',
          nik: '1234567890123456',
          tempatLahir: 'Jakarta',
          tanggalLahir: '01-01-1990',
          provinsi: 'DKI Jakarta',
          foto: '/assets/ilustrasi.png',
          qrCode: '/assets/ilustrasi.png',
          whatsapp: '08123456789',
          status: 'Active',
        },
        {
          no: 2,
          namaAnggota: 'Jane Doe',
          npa: '67890',
          nik: '6543210987654321',
          tempatLahir: 'Bandung',
          tanggalLahir: '02-02-1992',
          provinsi: 'Jawa Barat',
          foto: '/icon/pencil.png',
          qrCode: '/assets/ilustrasi.png',
          whatsapp: '08198765432',
          status: 'Inactive',
        },
        {
          no: 3,
          namaAnggota: 'Muhammad Salman alfarisi S.Kom',
          npa: '12345',
          nik: '1234567890123456',
          tempatLahir: 'Jakarta',
          tanggalLahir: '01-01-1990',
          provinsi: 'DKI Jakarta',
          foto: '/assets/ilustrasi.png',
          qrCode: '/assets/ilustrasi.png',
          whatsapp: '08123456789',
          status: 'Active',
        },
        {
          no: 4,
          namaAnggota: 'Aisyah nurul Hasanah S.Pd',
          npa: '12345',
          nik: '1234567890123456',
          tempatLahir: 'Jakarta',
          tanggalLahir: '01-01-1990',
          provinsi: 'DKI Jakarta',
          foto: '/assets/ilustrasi.png',
          qrCode: '/assets/ilustrasi.png',
          whatsapp: '08123456789',
          status: 'Active',
        },
        {
          no: 1,
          namaAnggota: 'Muhammad Abdul HAlim S.Kom',
          npa: '12345',
          nik: '1234567890123456',
          tempatLahir: 'Jakarta',
          tanggalLahir: '01-01-1990',
          provinsi: 'DKI Jakarta',
          foto: '/assets/ilustrasi.png',
          qrCode: '/assets/ilustrasi.png',
          whatsapp: '08123456789',
          status: 'Active',
        },
        {
          no: 2,
          namaAnggota: 'Jane Doe',
          npa: '67890',
          nik: '6543210987654321',
          tempatLahir: 'Bandung',
          tanggalLahir: '02-02-1992',
          provinsi: 'Jawa Barat',
          foto: '/icon/pencil.png',
          qrCode: '/assets/ilustrasi.png',
          whatsapp: '08198765432',
          status: 'Inactive',
        },
        {
          no: 3,
          namaAnggota: 'Muhammad Salman alfarisi S.Kom',
          npa: '12345',
          nik: '1234567890123456',
          tempatLahir: 'Jakarta',
          tanggalLahir: '01-01-1990',
          provinsi: 'DKI Jakarta',
          foto: '/assets/ilustrasi.png',
          qrCode: '/assets/ilustrasi.png',
          whatsapp: '08123456789',
          status: 'Active',
        },
        {
          no: 4,
          namaAnggota: 'Aisyah nurul Hasanah S.Pd',
          npa: '12345',
          nik: '1234567890123456',
          tempatLahir: 'Jakarta',
          tanggalLahir: '01-01-1990',
          provinsi: 'DKI Jakarta',
          foto: '/assets/ilustrasi.png',
          qrCode: '/assets/ilustrasi.png',
          whatsapp: '08123456789',
          status: 'Active',
        },
        {
            no: 1,
            namaAnggota: 'Muhammad Abdul HAlim S.Kom',
            npa: '12345',
            nik: '1234567890123456',
            tempatLahir: 'Jakarta',
            tanggalLahir: '01-01-1990',
            provinsi: 'DKI Jakarta',
            foto: '/assets/ilustrasi.png',
            qrCode: '/assets/ilustrasi.png',
            whatsapp: '08123456789',
            status: 'Active',
          },
          {
            no: 2,
            namaAnggota: 'Jane Doe',
            npa: '67890',
            nik: '6543210987654321',
            tempatLahir: 'Bandung',
            tanggalLahir: '02-02-1992',
            provinsi: 'Jawa Barat',
            foto: '/icon/pencil.png',
            qrCode: '/assets/ilustrasi.png',
            whatsapp: '08198765432',
            status: 'Inactive',
          },
          {
            no: 3,
            namaAnggota: 'Muhammad Salman alfarisi S.Kom',
            npa: '12345',
            nik: '1234567890123456',
            tempatLahir: 'Jakarta',
            tanggalLahir: '01-01-1990',
            provinsi: 'DKI Jakarta',
            foto: '/assets/ilustrasi.png',
            qrCode: '/assets/ilustrasi.png',
            whatsapp: '08123456789',
            status: 'Active',
          },
          {
            no: 4,
            namaAnggota: 'Aisyah nurul Hasanah S.Pd',
            npa: '12345',
            nik: '1234567890123456',
            tempatLahir: 'Jakarta',
            tanggalLahir: '01-01-1990',
            provinsi: 'DKI Jakarta',
            foto: '/assets/ilustrasi.png',
            qrCode: '/assets/ilustrasi.png',
            whatsapp: '08123456789',
            status: 'Active',
          },
          {
              no: 1,
              namaAnggota: 'Muhammad Abdul HAlim S.Kom',
              npa: '12345',
              nik: '1234567890123456',
              tempatLahir: 'Jakarta',
              tanggalLahir: '01-01-1990',
              provinsi: 'DKI Jakarta',
              foto: '/assets/ilustrasi.png',
              qrCode: '/assets/ilustrasi.png',
              whatsapp: '08123456789',
              status: 'Active',
            },
            {
              no: 2,
              namaAnggota: 'Jane Doe',
              npa: '67890',
              nik: '6543210987654321',
              tempatLahir: 'Bandung',
              tanggalLahir: '02-02-1992',
              provinsi: 'Jawa Barat',
              foto: '/icon/pencil.png',
              qrCode: '/assets/ilustrasi.png',
              whatsapp: '08198765432',
              status: 'Inactive',
            },
            {
              no: 3,
              namaAnggota: 'Muhammad Salman alfarisi S.Kom',
              npa: '12345',
              nik: '1234567890123456',
              tempatLahir: 'Jakarta',
              tanggalLahir: '01-01-1990',
              provinsi: 'DKI Jakarta',
              foto: '/assets/ilustrasi.png',
              qrCode: '/assets/ilustrasi.png',
              whatsapp: '08123456789',
              status: 'Active',
            },
            {
              no: 4,
              namaAnggota: 'Aisyah nurul Hasanah S.Pd',
              npa: '12345',
              nik: '1234567890123456',
              tempatLahir: 'Jakarta',
              tanggalLahir: '01-01-1990',
              provinsi: 'DKI Jakarta',
              foto: '/assets/ilustrasi.png',
              qrCode: '/assets/ilustrasi.png',
              whatsapp: '08123456789',
              status: 'Active',
            },
            {
              no: 1,
              namaAnggota: 'Muhammad Abdul HAlim S.Kom',
              npa: '12345',
              nik: '1234567890123456',
              tempatLahir: 'Jakarta',
              tanggalLahir: '01-01-1990',
              provinsi: 'DKI Jakarta',
              foto: '/assets/ilustrasi.png',
              qrCode: '/assets/ilustrasi.png',
              whatsapp: '08123456789',
              status: 'Active',
            },
            {
              no: 2,
              namaAnggota: 'Jane Doe',
              npa: '67890',
              nik: '6543210987654321',
              tempatLahir: 'Bandung',
              tanggalLahir: '02-02-1992',
              provinsi: 'Jawa Barat',
              foto: '/icon/pencil.png',
              qrCode: '/assets/ilustrasi.png',
              whatsapp: '08198765432',
              status: 'Inactive',
            },
            {
              no: 3,
              namaAnggota: 'Muhammad Salman alfarisi S.Kom',
              npa: '12345',
              nik: '1234567890123456',
              tempatLahir: 'Jakarta',
              tanggalLahir: '01-01-1990',
              provinsi: 'DKI Jakarta',
              foto: '/assets/ilustrasi.png',
              qrCode: '/assets/ilustrasi.png',
              whatsapp: '08123456789',
              status: 'Active',
            },
            {
              no: 4,
              namaAnggota: 'Aisyah nurul Hasanah S.Pd',
              npa: '12345',
              nik: '1234567890123456',
              tempatLahir: 'Jakarta',
              tanggalLahir: '01-01-1990',
              provinsi: 'DKI Jakarta',
              foto: '/assets/ilustrasi.png',
              qrCode: '/assets/ilustrasi.png',
              whatsapp: '08123456789',
              status: 'Active',
            },
            {
                no: 1,
                namaAnggota: 'Muhammad Abdul HAlim S.Kom',
                npa: '12345',
                nik: '1234567890123456',
                tempatLahir: 'Jakarta',
                tanggalLahir: '01-01-1990',
                provinsi: 'DKI Jakarta',
                foto: '/assets/ilustrasi.png',
                qrCode: '/assets/ilustrasi.png',
                whatsapp: '08123456789',
                status: 'Active',
              },
              {
                no: 2,
                namaAnggota: 'Jane Doe',
                npa: '67890',
                nik: '6543210987654321',
                tempatLahir: 'Bandung',
                tanggalLahir: '02-02-1992',
                provinsi: 'Jawa Barat',
                foto: '/icon/pencil.png',
                qrCode: '/assets/ilustrasi.png',
                whatsapp: '08198765432',
                status: 'Inactive',
              },
              {
                no: 3,
                namaAnggota: 'Muhammad Salman alfarisi S.Kom',
                npa: '12345',
                nik: '1234567890123456',
                tempatLahir: 'Jakarta',
                tanggalLahir: '01-01-1990',
                provinsi: 'DKI Jakarta',
                foto: '/assets/ilustrasi.png',
                qrCode: '/assets/ilustrasi.png',
                whatsapp: '08123456789',
                status: 'Active',
              },
              {
                no: 4,
                namaAnggota: 'Aisyah nurul Hasanah S.Pd',
                npa: '12345',
                nik: '1234567890123456',
                tempatLahir: 'Jakarta',
                tanggalLahir: '01-01-1990',
                provinsi: 'DKI Jakarta',
                foto: '/assets/ilustrasi.png',
                qrCode: '/assets/ilustrasi.png',
                whatsapp: '08123456789',
                status: 'Active',
              },
              {
                  no: 1,
                  namaAnggota: 'Muhammad Abdul HAlim S.Kom',
                  npa: '12345',
                  nik: '1234567890123456',
                  tempatLahir: 'Jakarta',
                  tanggalLahir: '01-01-1990',
                  provinsi: 'DKI Jakarta',
                  foto: '/assets/ilustrasi.png',
                  qrCode: '/assets/ilustrasi.png',
                  whatsapp: '08123456789',
                  status: 'Active',
                },
                {
                  no: 2,
                  namaAnggota: 'Jane Doe',
                  npa: '67890',
                  nik: '6543210987654321',
                  tempatLahir: 'Bandung',
                  tanggalLahir: '02-02-1992',
                  provinsi: 'Jawa Barat',
                  foto: '/icon/pencil.png',
                  qrCode: '/assets/ilustrasi.png',
                  whatsapp: '08198765432',
                  status: 'Inactive',
                },
                {
                  no: 3,
                  namaAnggota: 'Muhammad Salman alfarisi S.Kom',
                  npa: '12345',
                  nik: '1234567890123456',
                  tempatLahir: 'Jakarta',
                  tanggalLahir: '01-01-1990',
                  provinsi: 'DKI Jakarta',
                  foto: '/assets/ilustrasi.png',
                  qrCode: '/assets/ilustrasi.png',
                  whatsapp: '08123456789',
                  status: 'Active',
                },
                {
                  no: 4,
                  namaAnggota: 'Aisyah nurul Hasanah S.Pd',
                  npa: '12345',
                  nik: '1234567890123456',
                  tempatLahir: 'Jakarta',
                  tanggalLahir: '01-01-1990',
                  provinsi: 'DKI Jakarta',
                  foto: '/assets/ilustrasi.png',
                  qrCode: '/assets/ilustrasi.png',
                  whatsapp: '08123456789',
                  status: 'Active',
                },
                {
                  no: 1,
                  namaAnggota: 'Muhammad Abdul HAlim S.Kom',
                  npa: '12345',
                  nik: '1234567890123456',
                  tempatLahir: 'Jakarta',
                  tanggalLahir: '01-01-1990',
                  provinsi: 'DKI Jakarta',
                  foto: '/assets/ilustrasi.png',
                  qrCode: '/assets/ilustrasi.png',
                  whatsapp: '08123456789',
                  status: 'Active',
                },
                {
                  no: 2,
                  namaAnggota: 'Jane Doe',
                  npa: '67890',
                  nik: '6543210987654321',
                  tempatLahir: 'Bandung',
                  tanggalLahir: '02-02-1992',
                  provinsi: 'Jawa Barat',
                  foto: '/icon/pencil.png',
                  qrCode: '/assets/ilustrasi.png',
                  whatsapp: '08198765432',
                  status: 'Inactive',
                },
                {
                  no: 3,
                  namaAnggota: 'Muhammad Salman alfarisi S.Kom',
                  npa: '12345',
                  nik: '1234567890123456',
                  tempatLahir: 'Jakarta',
                  tanggalLahir: '01-01-1990',
                  provinsi: 'DKI Jakarta',
                  foto: '/assets/ilustrasi.png',
                  qrCode: '/assets/ilustrasi.png',
                  whatsapp: '08123456789',
                  status: 'Active',
                },
                {
                  no: 4,
                  namaAnggota: 'Aisyah nurul Hasanah S.Pd',
                  npa: '12345',
                  nik: '1234567890123456',
                  tempatLahir: 'Jakarta',
                  tanggalLahir: '01-01-1990',
                  provinsi: 'DKI Jakarta',
                  foto: '/assets/ilustrasi.png',
                  qrCode: '/assets/ilustrasi.png',
                  whatsapp: '08123456789',
                  status: 'Active',
                },
                {
                  no: 1,
                  namaAnggota: 'Muhammad Abdul HAlim S.Kom',
                  npa: '12345',
                  nik: '1234567890123456',
                  tempatLahir: 'Jakarta',
                  tanggalLahir: '01-01-1990',
                  provinsi: 'DKI Jakarta',
                  foto: '/assets/ilustrasi.png',
                  qrCode: '/assets/ilustrasi.png',
                  whatsapp: '08123456789',
                  status: 'Active',
                },
                {
                  no: 2,
                  namaAnggota: 'Jane Doe',
                  npa: '67890',
                  nik: '6543210987654321',
                  tempatLahir: 'Bandung',
                  tanggalLahir: '02-02-1992',
                  provinsi: 'Jawa Barat',
                  foto: '/icon/pencil.png',
                  qrCode: '/assets/ilustrasi.png',
                  whatsapp: '08198765432',
                  status: 'Inactive',
                },
                {
                  no: 3,
                  namaAnggota: 'Muhammad Salman alfarisi S.Kom',
                  npa: '12345',
                  nik: '1234567890123456',
                  tempatLahir: 'Jakarta',
                  tanggalLahir: '01-01-1990',
                  provinsi: 'DKI Jakarta',
                  foto: '/assets/ilustrasi.png',
                  qrCode: '/assets/ilustrasi.png',
                  whatsapp: '08123456789',
                  status: 'Active',
                },
                {
                  no: 4,
                  namaAnggota: 'Aisyah nurul Hasanah S.Pd',
                  npa: '12345',
                  nik: '1234567890123456',
                  tempatLahir: 'Jakarta',
                  tanggalLahir: '01-01-1990',
                  provinsi: 'DKI Jakarta',
                  foto: '/assets/ilustrasi.png',
                  qrCode: '/assets/ilustrasi.png',
                  whatsapp: '08123456789',
                  status: 'Active',
                },
                {
                    no: 1,
                    namaAnggota: 'Muhammad Abdul HAlim S.Kom',
                    npa: '12345',
                    nik: '1234567890123456',
                    tempatLahir: 'Jakarta',
                    tanggalLahir: '01-01-1990',
                    provinsi: 'DKI Jakarta',
                    foto: '/assets/ilustrasi.png',
                    qrCode: '/assets/ilustrasi.png',
                    whatsapp: '08123456789',
                    status: 'Active',
                  },
                  {
                    no: 2,
                    namaAnggota: 'Jane Doe',
                    npa: '67890',
                    nik: '6543210987654321',
                    tempatLahir: 'Bandung',
                    tanggalLahir: '02-02-1992',
                    provinsi: 'Jawa Barat',
                    foto: '/icon/pencil.png',
                    qrCode: '/assets/ilustrasi.png',
                    whatsapp: '08198765432',
                    status: 'Inactive',
                  },
                  {
                    no: 3,
                    namaAnggota: 'Muhammad Salman alfarisi S.Kom',
                    npa: '12345',
                    nik: '1234567890123456',
                    tempatLahir: 'Jakarta',
                    tanggalLahir: '01-01-1990',
                    provinsi: 'DKI Jakarta',
                    foto: '/assets/ilustrasi.png',
                    qrCode: '/assets/ilustrasi.png',
                    whatsapp: '08123456789',
                    status: 'Active',
                  },
                  {
                    no: 4,
                    namaAnggota: 'Aisyah nurul Hasanah S.Pd',
                    npa: '12345',
                    nik: '1234567890123456',
                    tempatLahir: 'Jakarta',
                    tanggalLahir: '01-01-1990',
                    provinsi: 'DKI Jakarta',
                    foto: '/assets/ilustrasi.png',
                    qrCode: '/assets/ilustrasi.png',
                    whatsapp: '08123456789',
                    status: 'Active',
                  },
                  {
                    no: 1,
                    namaAnggota: 'Muhammad Abdul HAlim S.Kom',
                    npa: '12345',
                    nik: '1234567890123456',
                    tempatLahir: 'Jakarta',
                    tanggalLahir: '01-01-1990',
                    provinsi: 'DKI Jakarta',
                    foto: '/assets/ilustrasi.png',
                    qrCode: '/assets/ilustrasi.png',
                    whatsapp: '08123456789',
                    status: 'Active',
                  },
                  {
                    no: 2,
                    namaAnggota: 'Jane Doe',
                    npa: '67890',
                    nik: '6543210987654321',
                    tempatLahir: 'Bandung',
                    tanggalLahir: '02-02-1992',
                    provinsi: 'Jawa Barat',
                    foto: '/icon/pencil.png',
                    qrCode: '/assets/ilustrasi.png',
                    whatsapp: '08198765432',
                    status: 'Inactive',
                  },
                  {
                    no: 3,
                    namaAnggota: 'Muhammad Salman alfarisi S.Kom',
                    npa: '12345',
                    nik: '1234567890123456',
                    tempatLahir: 'Jakarta',
                    tanggalLahir: '01-01-1990',
                    provinsi: 'DKI Jakarta',
                    foto: '/assets/ilustrasi.png',
                    qrCode: '/assets/ilustrasi.png',
                    whatsapp: '08123456789',
                    status: 'Active',
                  },
                  {
                    no: 4,
                    namaAnggota: 'Aisyah nurul Hasanah S.Pd',
                    npa: '12345',
                    nik: '1234567890123456',
                    tempatLahir: 'Jakarta',
                    tanggalLahir: '01-01-1990',
                    provinsi: 'DKI Jakarta',
                    foto: '/assets/ilustrasi.png',
                    qrCode: '/assets/ilustrasi.png',
                    whatsapp: '08123456789',
                    status: 'Active',
                  },
                  {
                      no: 1,
                      namaAnggota: 'Muhammad Abdul HAlim S.Kom',
                      npa: '12345',
                      nik: '1234567890123456',
                      tempatLahir: 'Jakarta',
                      tanggalLahir: '01-01-1990',
                      provinsi: 'DKI Jakarta',
                      foto: '/assets/ilustrasi.png',
                      qrCode: '/assets/ilustrasi.png',
                      whatsapp: '08123456789',
                      status: 'Active',
                    },
                    {
                      no: 2,
                      namaAnggota: 'Jane Doe',
                      npa: '67890',
                      nik: '6543210987654321',
                      tempatLahir: 'Bandung',
                      tanggalLahir: '02-02-1992',
                      provinsi: 'Jawa Barat',
                      foto: '/icon/pencil.png',
                      qrCode: '/assets/ilustrasi.png',
                      whatsapp: '08198765432',
                      status: 'Inactive',
                    },
                    {
                      no: 3,
                      namaAnggota: 'Muhammad Salman alfarisi S.Kom',
                      npa: '12345',
                      nik: '1234567890123456',
                      tempatLahir: 'Jakarta',
                      tanggalLahir: '01-01-1990',
                      provinsi: 'DKI Jakarta',
                      foto: '/assets/ilustrasi.png',
                      qrCode: '/assets/ilustrasi.png',
                      whatsapp: '08123456789',
                      status: 'Active',
                    },
                    {
                      no: 4,
                      namaAnggota: 'Aisyah nurul Hasanah S.Pd',
                      npa: '12345',
                      nik: '1234567890123456',
                      tempatLahir: 'Jakarta',
                      tanggalLahir: '01-01-1990',
                      provinsi: 'DKI Jakarta',
                      foto: '/assets/ilustrasi.png',
                      qrCode: '/assets/ilustrasi.png',
                      whatsapp: '08123456789',
                      status: 'Active',
                    },
                    {
                        no: 1,
                        namaAnggota: 'Muhammad Abdul HAlim S.Kom',
                        npa: '12345',
                        nik: '1234567890123456',
                        tempatLahir: 'Jakarta',
                        tanggalLahir: '01-01-1990',
                        provinsi: 'DKI Jakarta',
                        foto: '/assets/ilustrasi.png',
                        qrCode: '/assets/ilustrasi.png',
                        whatsapp: '08123456789',
                        status: 'Active',
                      },
                      {
                        no: 2,
                        namaAnggota: 'Jane Doe',
                        npa: '67890',
                        nik: '6543210987654321',
                        tempatLahir: 'Bandung',
                        tanggalLahir: '02-02-1992',
                        provinsi: 'Jawa Barat',
                        foto: '/icon/pencil.png',
                        qrCode: '/assets/ilustrasi.png',
                        whatsapp: '08198765432',
                        status: 'Inactive',
                      },
                      {
                        no: 3,
                        namaAnggota: 'Muhammad Salman alfarisi S.Kom',
                        npa: '12345',
                        nik: '1234567890123456',
                        tempatLahir: 'Jakarta',
                        tanggalLahir: '01-01-1990',
                        provinsi: 'DKI Jakarta',
                        foto: '/assets/ilustrasi.png',
                        qrCode: '/assets/ilustrasi.png',
                        whatsapp: '08123456789',
                        status: 'Active',
                      },
                      {
                        no: 4,
                        namaAnggota: 'Aisyah nurul Hasanah S.Pd',
                        npa: '12345',
                        nik: '1234567890123456',
                        tempatLahir: 'Jakarta',
                        tanggalLahir: '01-01-1990',
                        provinsi: 'DKI Jakarta',
                        foto: '/assets/ilustrasi.png',
                        qrCode: '/assets/ilustrasi.png',
                        whatsapp: '08123456789',
                        status: 'Active',
                      },
                      {
                        no: 1,
                        namaAnggota: 'Muhammad Abdul HAlim S.Kom',
                        npa: '12345',
                        nik: '1234567890123456',
                        tempatLahir: 'Jakarta',
                        tanggalLahir: '01-01-1990',
                        provinsi: 'DKI Jakarta',
                        foto: '/assets/ilustrasi.png',
                        qrCode: '/assets/ilustrasi.png',
                        whatsapp: '08123456789',
                        status: 'Active',
                      },
                      {
                        no: 2,
                        namaAnggota: 'Jane Doe',
                        npa: '67890',
                        nik: '6543210987654321',
                        tempatLahir: 'Bandung',
                        tanggalLahir: '02-02-1992',
                        provinsi: 'Jawa Barat',
                        foto: '/icon/pencil.png',
                        qrCode: '/assets/ilustrasi.png',
                        whatsapp: '08198765432',
                        status: 'Inactive',
                      },
                      {
                        no: 3,
                        namaAnggota: 'Muhammad Salman alfarisi S.Kom',
                        npa: '12345',
                        nik: '1234567890123456',
                        tempatLahir: 'Jakarta',
                        tanggalLahir: '01-01-1990',
                        provinsi: 'DKI Jakarta',
                        foto: '/assets/ilustrasi.png',
                        qrCode: '/assets/ilustrasi.png',
                        whatsapp: '08123456789',
                        status: 'Active',
                      },
                      {
                        no: 4,
                        namaAnggota: 'Aisyah nurul Hasanah S.Pd',
                        npa: '12345',
                        nik: '1234567890123456',
                        tempatLahir: 'Jakarta',
                        tanggalLahir: '01-01-1990',
                        provinsi: 'DKI Jakarta',
                        foto: '/assets/ilustrasi.png',
                        qrCode: '/assets/ilustrasi.png',
                        whatsapp: '08123456789',
                        status: 'Active',
                      },
  ];